In [5]:
from datetime import datetime, timedelta
import dukascopy_python
from dukascopy_python.instruments import INSTRUMENT_FX_MAJORS_GBP_USD

In [6]:
start = datetime(2025, 1, 1)
end = datetime(2025, 2, 1)
instrument = INSTRUMENT_FX_MAJORS_GBP_USD
interval = dukascopy_python.INTERVAL_HOUR_1
offer_side = dukascopy_python.OFFER_SIDE_BID

df = dukascopy_python.fetch(
    instrument,
    interval,
    offer_side,
    start,
    end,
)

df

                              open     high      low    close    volume
timestamp
2025-01-01 22:00:00+00:00  1.25134  1.25150  1.25097  1.25125   1444.00
2025-01-01 23:00:00+00:00  1.25125  1.25194  1.25059  1.25193   7970.28
2025-01-02 00:00:00+00:00  1.25190  1.25203  1.25089  1.25161   4802.20
2025-01-02 01:00:00+00:00  1.25162  1.25220  1.25114  1.25196  12426.18
2025-01-02 02:00:00+00:00  1.25198  1.25331  1.25196  1.25331   2659.11
...                            ...      ...      ...      ...       ...
2025-01-31 17:00:00+00:00  1.24455  1.24715  1.24306  1.24534  18502.26
2025-01-31 18:00:00+00:00  1.24536  1.24611  1.23901  1.23960  15956.57
2025-01-31 19:00:00+00:00  1.23959  1.24055  1.23856  1.24002  11782.14
2025-01-31 20:00:00+00:00  1.24001  1.24093  1.23877  1.23993   9654.50
2025-01-31 21:00:00+00:00  1.23993  1.24107  1.23860  1.23919   9836.97

[528 rows x 5 columns]

In [7]:
import yfinance as yf

In [9]:
tickers = yf.Tickers('MSFT AAPL GOOG')
tickers.tickers['MSFT'].info
yf.download(['MSFT', 'AAPL', 'GOOG'], period='1mo')["Close"]

[*********************100%***********************]  3 of 3 completed

Ticker            AAPL        GOOG        MSFT
Date
2026-07-06  312.660004  364.899994  386.739990
2026-07-07  310.660004  363.619995  388.839996
2026-07-08  313.390015  358.709991  383.339996
2026-07-09  316.220001  356.239990  384.359985
2026-07-10  315.320007  355.029999  385.100006
2026-07-13  317.309998  350.670013  390.989990
2026-07-14  314.859985  357.329987  384.929993
2026-07-15  327.500000  370.209991  395.630005
2026-07-16  333.260010  353.809998  401.100006
2026-07-17  333.739990  346.119995  393.820007
2026-07-20  326.589996  351.369995  402.290009
2026-07-21  327.739990  346.190002  397.750000
2026-07-22  325.890015  341.910004  390.339996
2026-07-23  321.660004  318.339996  381.579987
2026-07-24  333.019989  319.089996  381.700012
2026-07-27  336.910004  326.570007  389.100006
2026-07-28  340.079987  332.600006  393.350006
2026-07-29  338.190002  335.760010  390.540009
2026-07-30  333.429993  333.679993  451.100006
2026-07-31  308.910004  356.649994  464.720001
2026-08-03  303.420013  372.470001  487.649994
2026-08-04  309.380005  375.350006  492.809998
2026-08-05  311.000000  360.130005  487.459991