In [41]:
import yfinance as yf

In [42]:
stock = yf.Ticker("UEC")

In [43]:
stock

yfinance.Ticker object <UEC>

In [44]:
stock.info

{'address1': '500 North Shoreline',
 'address2': 'Suite 800N',
 'city': 'Corpus Christi',
 'state': 'TX',
 'zip': '78401',
 'country': 'United States',
 'phone': '361 888 8235',
 'fax': '361 888 5041',
 'website': 'https://www.uraniumenergy.com',
 'industry': 'Uranium',
 'industryKey': 'uranium',
 'industryDisp': 'Uranium',
 'sector': 'Energy',
 'sectorKey': 'energy',
 'sectorDisp': 'Energy',
 'longBusinessSummary': 'Uranium Energy Corp., together with its subsidiaries, engages in exploration, pre-extraction, extraction, and processing of uranium and titanium concentrates properties in the United States, Canada, and the Republic of Paraguay. The company was formerly known as Carlin Gold Inc. and changed its name to Uranium Energy Corp. in January 2005. The company was incorporated in 2003 and is headquartered in Corpus Christi, Texas.',
 'fullTimeEmployees': 171,
 'companyOfficers': [{'maxAge': 1,
   'name': 'Mr. Amir  Adnani',
   'age': 47,
   'title': 'President, CEO & Director',
   'yearBorn': 1978,
   'fiscalYear': 2025,
   'totalPay': 2358193,
   'exercisedValue': 0,
   'unexercisedValue': 359301},
  {'maxAge': 1,
   'name': 'Ms. Josephine  Man',
   'age': 51,
   'title': 'Secretary, Treasurer, CFO & Principal Accounting Officer',
   'yearBorn': 1974,
   'fiscalYear': 2025,
   'totalPay': 360000,
   'exercisedValue': 0,
   'unexercisedValue': 550605},
  {'maxAge': 1,
   'name': 'Mr. Scott Eric Melbye',
   'age': 63,
   'title': 'Executive Vice President',
   'yearBorn': 1962,
   'fiscalYear': 2025,
   'totalPay': 719354,
   'exercisedValue': 0,
   'unexercisedValue': 3700408},
  {'maxAge': 1,
   'name': 'Mr. Brent D. Berg',
   'age': 53,
   'title': 'Senior Vice President of U.S. Operations',
   'yearBorn': 1972,
   'fiscalYear': 2025,
   'totalPay': 490000,
   'exercisedValue': 0,
   'unexercisedValue': 34942},
  {'maxAge': 1,
   'name': 'Ms. Donna Lynn Wichers',
   'age': 70,
   'title': 'Senior Vice President of Production Growth',
   'yearBorn': 1955,
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'auditRisk': 5,
 'boardRisk': 2,
 'compensationRisk': 1,
 'shareHolderRightsRisk': 2,
 'overallRisk': 1,
 'governanceEpochDate': 1785542400,
 'compensationAsOfEpochDate': 1767139200,
 'executiveTeam': [],
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 11.46,
 'open': 11.8,
 'dayLow': 11.3008,
 'dayHigh': 11.83,
 'regularMarketPreviousClose': 11.46,
 'regularMarketOpen': 11.8,
 'regularMarketDayLow': 11.3008,
 'regularMarketDayHigh': 11.83,
 'payoutRatio': 0.0,
 'beta': 1.208,
 'forwardPE': -126.22221,
 'volume': 4808193,
 'regularMarketVolume': 4808193,
 'averageVolume': 9853862,
 'averageVolume10days': 8402110,
 'averageDailyVolume10Day': 8402110,
 'bid': 11.31,
 'ask': 11.43,
 'bidSize': 2900,
 'askSize': 1300,
 'nonDilutedMarketCap': 5631647525,
 'fiftyTwoWeekLow': 8.91,
 'fiftyTwoWeekHigh': 20.34,
 'allTimeHigh': 20.34,
 'allTimeLow': 0.16,
 'fiftyDayAverage': 10.8224,
 'twoHundredDayAverage': 13.383,
 'trailingAnnualDividendRate': 0.0,
 'trailingAnnualDividendYield': 0.0,
 'currency': 'USD',
 'tradeable': False,
 'enterpriseValue': 5135609856,
 'profitMargins': 0.0,
 'floatShares': 482683660,
 'sharesShort': 59099804,
 'sharesShortPriorMonth': 61080807,
 'sharesShortPreviousMonthDate': 1782777600,
 'dateShortInterest': 1785456000,
 'sharesPercentSharesOut': 0.119399995,
 'heldPercentInsiders': 0.01856,
 'heldPercentInstitutions': 0.86901003,
 'shortRatio': 7.6,
 'shortPercentOfFloat': 0.1438,
 'lastFiscalYearEnd': 1753920000,
 'nextFiscalYearEnd': 1785456000,
 'mostRecentQuarter': 1777507200,
 'netIncomeToCommon': -103674000,
 'trailingEps': -0.22,
 'forwardEps': -0.09,
 'pegRatio': 1.37,
 'enterpriseToRevenue': 254.238,
 'enterpriseToEbitda': -42.527,
 '52WeekChange': 0.12133074,
 'SandP52WeekChange': 0.19509852,
 'quoteType': 'EQUITY',
 'currentPrice': 11.36,
 'targetHighPrice': 26.75,
 'targetLowPrice': 12.0,
 'targetMeanPrice': 18.02778,
 'targetMedianPrice': 17.0,
 'recommendationMean': 1.44444,
 'recommendationKey': 'strong_buy',
 'numberOfAnalystOpinions': 9,
 'totalCash': 488052992,
 'totalCashPerShare': 0.986,
 'ebitda': -120762000,
 'totalDebt': 1913000,
 'quickRatio': 27.411,
 'currentRatio': 32.667,
 'totalRevenue': 20200000,
 'debtToEquity': 0.135,
 'revenuePerShare': 0.043,
 'returnOnAssets': -0.06245,
 'returnOnEquity': -0.0896,
 'grossProfits': -79995000,
 'freeCashflow': -82066752,
 'operatingCashflow': -113513000,
 'grossMargins': 0.0,
 'ebitdaMargins': 0.0,
 'operatingMargins': -6.2965803,
 'financialCurrency': 'USD',
 'symbol': 'UEC',
 'language': 'en-US',
 'region': 'US',
 'typeDisp': 'Equity',
 'quoteSourceName': 'Nasdaq Real Time Price',
 'triggerable': True,
 'customPriceAlertConfidence': 'HIGH',
 'marketState': 'POSTPOST',
 'hasPrePostMarketData': True,
 'firstTradeDateMilliseconds': 1175779800000,
 'postMarketChangePercent': 0.61532146,
 'postMarketPrice': 11.4299,
 'postMarketChange': 0.06990051,
 'regularMarketChange': -0.1,
 'regularMarketDayRange': '11.3008 - 11.83',
 'fullExchangeName': 'NYSE American',
 'averageDailyVolume3Month': 9853862,
 'fiftyTwoWeekLowChange': 2.4499998,
 'fiftyTwoWeekLowChangePercent': 0.27497193,
 'fiftyTwoWeekRange': '8.91 - 20.34',
 'fiftyTwoWeekHighChange': -8.9800005,
 'fiftyTwoWeekHighChangePercent': -0.4414946,
 'fiftyTwoWeekChangePercent': 12.133074,
 'earningsTimestampStart': 1790253000,
 'earningsTimestampEnd': 1790253000,
 'earningsCallTimestampStart': 1781017200,
 'earningsCallTimestampEnd': 1781017200,
 'isEarningsDateEstimate': False,
 'epsTrailingTwelveMonths': -0.22,
 'epsForward': -0.09,
 'epsCurrentYear': -0.18333,
 'priceEpsCurrentYear': -61.96476,
 'fiftyDayAverageChange': 0.53759956,
 'fiftyDayAverageChangePercent': 0.04967471,
 'twoHundredDayAverageChange': -2.0230007,
 'twoHundredDayAverageChangePercent': -0.15116197,
 'sourceInterval': 15,
 'exchangeDataDelayedBy': 0,
 'averageAnalystRating': '1.4 - Strong Buy',
 'cryptoTradeable': False,
 'regularMarketChangePercent': -0.872604,
 'regularMarketPrice': 11.36,
 'corporateActions': [],
 'postMarketTime': 1786578994,
 'regularMarketTime': 1786564800,
 'exchange': 'ASE',
 'messageBoardId': 'finmb_23428489',
 'exchangeTimezoneName': 'America/New_York',
 'exchangeTimezoneShortName': 'EDT',
 'gmtOffSetMilliseconds': -14400000,
 'market': 'us_market',
 'esgPopulated': False,
 'shortName': 'Uranium Energy Corp.',
 'displayName': 'Uranium Energy',
 'trailingPegRatio': None}

In [45]:
stock.calendar

{'Earnings Date': [datetime.date(2026, 9, 24)],
 'Earnings High': -0.01,
 'Earnings Low': -0.01,
 'Earnings Average': -0.01,
 'Revenue High': 9000000,
 'Revenue Low': 9000000,
 'Revenue Average': 9000000}

In [46]:
stock.analyst_price_targets

{'current': 11.36,
 'high': 26.75,
 'low': 12.0,
 'mean': 18.02778,
 'median': 17.0}

In [47]:
stock.option_chain(stock.options[0]).calls

,contractSymbol,lastTradeDate,strike,lastPrice,bid,ask,change,percentChange,volume,openInterest,impliedVolatility,inTheMoney,contractSize,currency
0,UEC260814C00001000,2026-08-12 15:50:00+00:00,1.0,10.47,9.85,10.70,0.00,0.000000,38,7,29.625001,True,REGULAR,USD
1,UEC260814C00002000,2026-08-12 15:50:16+00:00,2.0,9.47,8.70,10.30,0.14,1.500539,61,12,15.562500,True,REGULAR,USD
2,UEC260814C00004000,2026-08-12 15:28:19+00:00,4.0,7.60,6.60,8.05,0.24,3.260866,6,13,15.500000,True,REGULAR,USD
3,UEC260814C00005000,2026-08-12 16:31:52+00:00,5.0,6.50,5.40,6.70,0.11,1.721442,7,10,9.828129,True,REGULAR,USD
4,UEC260814C00005500,2026-08-12 14:13:01+00:00,5.5,6.25,5.35,6.25,0.40,6.837608,6,9,9.265629,True,REGULAR,USD
5,UEC260814C00006000,2026-08-12 14:15:26+00:00,6.0,5.54,4.75,5.90,0.11,2.025785,6,7,9.406254,True,REGULAR,USD
6,UEC260814C00006500,2026-08-12 14:15:26+00:00,6.5,5.11,3.85,5.85,0.31,6.458332,1,5,11.062503,True,REGULAR,USD
7,UEC260814C00007000,2026-08-12 16:58:47+00:00,7.0,4.43,3.85,4.85,0.04,0.911161,7,4,7.375001,True,REGULAR,USD
8,UEC260814C00007500,2026-08-12 15:56:02+00:00,7.5,3.91,2.99,4.55,-0.03,-0.761421,6,9,7.656250,True,REGULAR,USD
9,UEC260814C00008500,2026-08-12 18:11:31+00:00,8.5,2.95,2.65,3.75,-0.20,-6.349207,2,2,4.484379,True,REGULAR,USD
10,UEC260814C00009000,2026-08-11 19:37:37+00:00,9.0,2.43,2.10,2.65,0.00,0.000000,4,1311,1.687502,True,REGULAR,USD
11,UEC260814C00009500,2026-08-10 13:30:01+00:00,9.5,1.85,1.75,2.12,0.00,0.000000,1,440,1.937500,True,REGULAR,USD
12,UEC260814C00010000,2026-08-12 17:51:30+00:00,10.0,1.46,1.24,1.52,0.06,4.285719,41,846,1.078130,True,REGULAR,USD
13,UEC260814C00010500,2026-08-12 18:27:44+00:00,10.5,0.95,0.76,1.13,-0.03,-3.061228,22,1663,1.132817,True,REGULAR,USD
14,UEC260814C00011000,2026-08-12 19:58:00+00:00,11.0,0.50,0.41,0.53,-0.04,-7.407411,1145,6474,0.757815,True,REGULAR,USD
15,UEC260814C00011500,2026-08-12 19:58:00+00:00,11.5,0.20,0.16,0.27,-0.07,-25.925928,57,740,0.828127,False,REGULAR,USD
16,UEC260814C00012000,2026-08-12 19:53:51+00:00,12.0,0.08,0.05,0.09,-0.03,-27.272728,134,1709,0.812502,False,REGULAR,USD
17,UEC260814C00012500,2026-08-12 17:39:19+00:00,12.5,0.01,0.01,0.03,-0.03,-75.000000,271,340,0.843752,False,REGULAR,USD
18,UEC260814C00013000,2026-08-12 17:00:15+00:00,13.0,0.01,0.00,0.02,0.00,0.000000,4,308,0.968750,False,REGULAR,USD
19,UEC260814C00013500,2026-08-10 19:56:55+00:00,13.5,0.01,0.00,0.10,0.00,0.000000,34,39,1.625002,False,REGULAR,USD
20,UEC260814C00014000,2026-08-11 19:46:09+00:00,14.0,0.01,0.00,0.01,0.00,0.000000,3,19,1.250004,False,REGULAR,USD
21,UEC260814C00014500,2026-07-16 15:08:42+00:00,14.5,0.05,0.00,0.27,0.00,0.000000,10,19,2.687503,False,REGULAR,USD
22,UEC260814C00015000,2026-08-11 19:45:51+00:00,15.0,0.01,0.00,0.27,0.00,0.000000,1,24,2.937503,False,REGULAR,USD
23,UEC260814C00015500,2026-08-04 13:57:05+00:00,15.5,0.04,0.00,0.20,0.00,0.000000,2,16,2.953128,False,REGULAR,USD

In [48]:
tickers = yf.Tickers('MSFT AAPL GOOG')

In [49]:
datos = yf.download(['UEC'], period='1mo')["Close"]

[*********************100%***********************]  1 of 1 completed

In [51]:
datos

Ticker        UEC
Date
2026-07-13  10.07
2026-07-14  10.39
2026-07-15  10.11
2026-07-16   9.33
2026-07-17   9.28
2026-07-20   9.40
2026-07-21   9.55
2026-07-22   9.73
2026-07-23   9.83
2026-07-24   9.51
2026-07-27   9.91
2026-07-28   9.44
2026-07-29   9.04
2026-07-30   9.74
2026-07-31   9.60
2026-08-03   9.97
2026-08-04  10.50
2026-08-05  10.72
2026-08-06  10.76
2026-08-07  11.26
2026-08-10  11.38
2026-08-11  11.46
2026-08-12  11.36

In [52]:
datos.to_excel("/workspaces/pizza-on-mondays/src/data/datos.xlsx")